ds.user.jdbc:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&amp;characterset=utf-8&useSSL=false
    username: root
    password: root

ds.log.jdbc:
    url: jdbc:mysql://localhost:3306/log?useUnicode=true&amp;characterset=utf-8&useSSL=false
    username: root
    password: root
